apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: mongo-argo-app
    namespace: argocd
spec:
    project: default

    source:
        repoURL: https://github.com/karansingh-amagi/kubernetes-helper.git
        targetRevision: HEAD
        path: mongo-argo
    destination:
        server: https://kubernetes.default.svc
        namespace: mongoapp

    syncPolicy:
        syncOptions:
            - CreateNamespace=true

        automated:
            selfHeal: true
            prune: true
